### ISSUE TITLE
Is there a pre-trained neural network?

### ISSUE THREAD

**Issue by sarimmehdi** [SmallMunich/nutonomy_pointpillars#14]
Hello. I really like your repository and I was hoping if you had a pre-trained neural net that I can use.

**Comment by deeptf** [comment]
@sarimmehdi Did you find a pre-trained weight? (or) If you had trained a network using this codebase, will you be able to share it with us? Thanks!

**Comment by JiyuanWANG12138** [comment]
> Hello. I really like your repository and I was hoping if you had a pre-trained neural net that I can use.

Hello ,do you find a pretrained model now?
