### ISSUE TITLE
Train a model for Autoware's Point Pillars ROS implementation ?

### ISSUE THREAD

**Issue by Reedeck** [SmallMunich/nutonomy_pointpillars#19]
Hello,

Can this code be used to train a model for Autoware's Point Pillars package ?

Thank you.

**Comment by chasingw** [comment]
hi @Reedeck , did you test it in autoware?
I test the model exported , but the result is too weird
![Screenshot from 2020-12-21 17-32-53](https://user-images.githubusercontent.com/2863603/102762179-e16a1e80-43b2-11eb-8027-3643557555af.png)

**Comment by ryontang** [comment]
> Hello,
> 
> Can this code be used to train a model for Autoware's Point Pillars package ?
> 
> Thank you.

@Reedeck Hi, do you solve this problem that use this code train a model for Autoware's PointPillars package?
