### ISSUE TITLE
ONXX format

### ISSUE THREAD

**Issue by MaxandreOgeret** [SmallMunich/nutonomy_pointpillars#3]
Hello, and thanks a lot for your work, it was really helpful !

I can't manage to export the ONXX file in a version that is suitable for my use. 
I need ONXX v3 and your program is exporting v4.

Do you know how I could change this ? Thanks ! :)

**Comment by SmallMunich** [comment]
onnx v3 export it well. you re-train model and export it with your onnx version.

**Comment by MaxandreOgeret** [comment]
Thanks for your answer ! 

Should I downgrade my Tensorrt version or change the `torch.onnx.export` function parameters in `train.py` ?

**Comment by SmallMunich** [comment]
> Thanks for your answer !
> 
> Should I downgrade my Tensorrt version or change the `torch.onnx.export` function parameters in `train.py` ?

change TensorRT version maybe better.
