### ISSUE TITLE
VoxelNet state_dict error

### ISSUE THREAD

**Issue by enesozi** [SmallMunich/nutonomy_pointpillars#4]
Hi,
I trained a network using the original [repository](https://github.com/nutonomy/second.pytorch). I'm getting the following error when I use this repository to convert the model to ONNX model. Do you have any idea what could be the reason? I can use my model for inference without any problem but conversion is giving me trouble.
TIA,

`RuntimeError: Error(s) in loading state_dict for VoxelNet:
Missing key(s) in state_dict: "voxel_feature_extractor.pfn_layers.0.conv1.weight", "voxel_feature_extractor.pfn_layers.0.conv1.bias", "voxel_feature_extractor.pfn_layers.0.conv2.weight", "voxel_feature_extractor.pfn_layers.0.conv2.bias", "voxel_feature_extractor.pfn_layers.0.t_conv.weight", "voxel_feature_extractor.pfn_layers.0.t_conv.bias", "voxel_feature_extractor.pfn_layers.0.conv3.weight", "voxel_feature_extractor.pfn_layers.0.conv3.bias". `

**Comment by enesozi** [comment]
Hi,
I ended up using the original repository to convert the model to onnx model. I think you've made changes in the source code so that model input could be compatible with the autoware package.

**Comment by z393** [comment]
Can u share your code? thanks
