### ISSUE TITLE
docker pull failed

### ISSUE THREAD

**Issue by sdu2011** [SmallMunich/nutonomy_pointpillars#5]
sudo docker pull smallmunich/suke_pointpillars:v0

Error response from daemon: manifest for smallmunich/suke_pointpillars:v0 not found: manifest unknown: manifest unknown

environment:
ubuntu 16.04
Docker version 19.03.7

**Comment by SmallMunich** [comment]
my pc environment:
ubuntu 18.04

**Comment by hz3014** [comment]
> 
> 
> sudo docker pull smallmunich/suke_pointpillars:v0
> 
> Error response from daemon: manifest for smallmunich/suke_pointpillars:v0 not found: manifest unknown: manifest unknown
> 
> environment:
> ubuntu 16.04
> Docker version 19.03.7

I am facing the same issue, wondering how you solved it?

**Comment by hz3014** [comment]
> 
> 
> my pc environment:
> ubuntu 18.04

Would you please check if the docker image is damaged, googled same error code and the problem was solved when the image was reuploaded. Thank you

**Comment by sdu2011** [comment]
> > sudo docker pull smallmunich/suke_pointpillars:v0
> > Error response from daemon: manifest for smallmunich/suke_pointpillars:v0 not found: manifest unknown: manifest unknown
> > environment:
> > ubuntu 16.04
> > Docker version 19.03.7
> 
> I am facing the same issue, wondering how you solved it?

no,i think the docker image is damaged．i do not think there is relationship with ubuntu version.
