### ISSUE TITLE
AssertionError: something write with training output size!

### ISSUE THREAD

**Issue by hz3014** [SmallMunich/nutonomy_pointpillars#9]
Hi, I followed your instructions step by step. After successfully created the data, I started training xyre_16.proto. However there is some error as follows:
File "/root/train_pointpillars/nutonomy_pointpillars/second/pytorch/train.py", line 312, in train
    assert 10 == len(ret_dict), "something write with training output size!"
AssertionError: something write with training output size!

Any suggectsion would be helpful! Thank you!

**Comment by SmallMunich** [comment]
please check your network structure, the output is not correspond.
